### ISSUE TITLE
python以及pylink版本问题

### ISSUE THREAD

**Issue by ZhaoJake** [tianxiaoMCU/RTT2UART#2]
您好，请问最新工程依赖的python版本是什么呢？
V1.4.0版本描述说pylink更新到0.8.1，可是最新版只能找到0.3.3，麻烦请解答，谢谢！

**Comment by tianxiaoMCU** [comment]
1. python 版本是V3.7.6
2. pylink 如果通过PyPI无法更新到最新，可以到[此处](https://github.com/square/pylink/releases)下载
